### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by BrunoLagoa** [marcelobdsilva/busman#2]
Olá, pode tirar uma dúvida.
Eu criei uma conta com o valor inicial de R$240,32.
Em despesas eu adicionei o valor de R$51,85 e efetuei o pagamento do mesmo.
No dashboard, mostra o valor pago em PAGO NO MÊS e o valor de R$240,32 no SALDO ATUAL.
No saldo atual, não deveria ter deduzido o valor pago? ficando com R$188,47. Segue print abaixo:
http://prntscr.com/fxxdu9

Não sei se estou entendendo errado, mais acho que ai deve ser o valor real que tem em conta. Não sei se e um bug ou erro de interpretação.

Abraço,

**Comment by marcelobdsilva** [comment]
Olá Bruno! 

De fato se fez tudo como no descrito, deveria ter subtraído do saldo atual. Tente fazer novamente a operação para ver se ocorre o mesmo.

Estou trabalhando em uma versão refatorada que corrigirá este e outros problemas.

Assine o repositório para receber notificação quando atualizar

**Comment by BrunoLagoa** [comment]
Olá,
eu apaguei todo o projeto e clonei novamente, assim funcionou. rs
já assinei. Obrigado,
